
server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cn.peixun.entity.Student


